name: STEVAL-MKBOXPRO-Audio Continuous Integration
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*'
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '*'
      - '**.md'
      - '**.txt'
jobs:
  astyle_check:
    runs-on: ubuntu-latest
    name: AStyle check
    steps:
    # First of all, clone the repo using the checkout action.
    - name: Checkout
      uses: actions/checkout@main

    - name: Astyle check
      id: Astyle
      uses: stm32duino/actions/astyle-check@main

    # Use the output from the `Astyle` step
    - name: Astyle Errors
      if: failure()
      run: |
        cat ${{ steps.Astyle.outputs.astyle-result }}
        exit 1
  spell-check:
    runs-on: ubuntu-latest
    name: Spell check
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Spell check
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_file: ./extras/codespell-ignore-words-list.txt
  # lib_build:
  #   runs-on: ubuntu-latest
  #   name: Library compilation
  #   steps:

  #   # First of all, clone the repo using the checkout action.
  #   - name: Checkout
  #     uses: actions/checkout@main

  #   - name: Compilation
  #     id: compile
  #     uses: stm32duino/actions/compile-examples@main
  #     with:
  #       board-pattern: "NUCLEO_L476RG"

  #   # Use the output from the `Compilation` step
  #   - name: Compilation Errors
  #     if: failure()
  #     run: |
  #       cat ${{ steps.compile.outputs.compile-result }}
  #       exit 1
